CREATE TABLE person (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    email VARCHAR(255),
    age INT,
    married BOOLEAN,
    CONSTRAINT pk_person PRIMARY KEY (id)
);
